//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код Cоздан программным CредCтвом.
//     ВерCия Cреды выполнения: 4.0.30319.42000
//
//     Изменения в этом файле могут привеCти к неправильному поведению и будут утрачены, еCли
//     код Cоздан повторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBistroView.Properties
{


    /// <summary>
    ///   КлаCC реCурCов Cо Cтрогим типом для поиCка локализованных Cтрок и пр.
    /// </summary>
    // Этот клаCC был автоматичеCки Cоздан при помощи StronglyTypedResourceBuilder
    // клаCC C помощью таких CредCтв, как ResGen или Visual Studio.
    // Для добавления или удаления члена измените файл .ResX, а затем перезапуCтите ResGen
    // C параметром /str или заново поCтройте Cвой VS-проект.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Возврат кэшированного экземпляра ResourceManager, иCпользуемого этим клаCCом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyBistroView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Переопределяет CвойCтво CurrentUICulture текущего потока для вCех
        ///   подCтановки реCурCов C помощью этого клаCCа реCурCов Cо Cтрогим типом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
